<main>
	<div class="content">
		<h2>Stigatafla</h2>
		<table>
			<thead>
				<tr>
					<th>Nafn:</th>
					<th>Stig:</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><strong>Nafn1</strong></td>
					<td>Stig1</td>
				</tr>
				<tr>
					<td><strong>Nafn2</strong></td>
					<td>Stig2</td>
				</tr>
				<tr>
					<td><strong>Nafn3</strong></td>
					<td>Stig3</td>
				</tr>
				<tr>
					<td><strong>Nafn4</strong></td>
					<td>Stig4</td>
				</tr>					
				<tr>
					<td><strong>Nafn5</strong></td>
					<td>Stig5</td>
				</tr>
			</tbody>
		</table>
	</div>
</main>